BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB


BBBBB BBB
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBB
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBB
    BBB BBBBBBB BB BBBBBBBBBBB
        XXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX
            XXXXX
        XXXXX
    BBBBBB
BBBBBBBB